// levels.js — all level definitions

const LEVELS = [
  {
    id: 1,
    title: "AND Gate",
    description: "Connect both inputs through an AND gate. Output is 1 only when BOTH inputs are 1.",
    hint: "AND = both must be ON",
    inputs: { A: 1, B: 1 },
    targetOutput: 1,
    availableGates: ["AND"],
    par: 1,
    introGate: "AND",
  },
  {
    id: 2,
    title: "OR Gate",
    description: "Make the output 1. Either input being 1 is enough.",
    hint: "OR = at least one must be ON",
    inputs: { A: 0, B: 1 },
    targetOutput: 1,
    availableGates: ["OR"],
    par: 1,
    introGate: "OR",
  },
  {
    id: 3,
    title: "NOT Gate",
    description: "Flip the input. A is 0 — make the output 1.",
    hint: "NOT flips the signal",
    inputs: { A: 0 },
    targetOutput: 1,
    availableGates: ["NOT"],
    par: 1,
    introGate: "NOT",
  },
  {
    id: 4,
    title: "AND + NOT",
    description: "A=1, B=0. Make output 1. You'll need two gates.",
    hint: "NOT one input, then AND them",
    inputs: { A: 1, B: 0 },
    targetOutput: 1,
    availableGates: ["AND", "NOT"],
    par: 2,
  },
  {
    id: 5,
    title: "XOR Gate",
    description: "Output is 1 when inputs DIFFER. A=1, B=0.",
    hint: "XOR = one OR the other, but not both",
    inputs: { A: 1, B: 0 },
    targetOutput: 1,
    availableGates: ["XOR"],
    par: 1,
    introGate: "XOR",
  },
  {
    id: 6,
    title: "NAND Gate",
    description: "Opposite of AND. A=1, B=1 — make output 1.",
    hint: "NAND = NOT AND",
    inputs: { A: 1, B: 1 },
    targetOutput: 0,
    availableGates: ["NAND"],
    par: 1,
    introGate: "NAND",
  },
  {
    id: 7,
    title: "NOR Gate",
    description: "Output is 1 only when BOTH inputs are 0. A=0, B=0.",
    hint: "NOR = NOT OR",
    inputs: { A: 0, B: 0 },
    targetOutput: 1,
    availableGates: ["NOR"],
    par: 1,
    introGate: "NOR",
  },
  {
    id: 8,
    title: "Two-Gate Challenge",
    description: "A=1, B=1, C=0. Make output 1. Think carefully.",
    hint: "Try OR then AND, or AND then OR",
    inputs: { A: 1, B: 1, C: 0 },
    targetOutput: 1,
    availableGates: ["AND", "OR", "NOT"],
    par: 2,
  },
  {
    id: 9,
    title: "Three-Gate Puzzle",
    description: "A=1, B=0, C=1. Make output 0.",
    hint: "Combine gates step by step",
    inputs: { A: 1, B: 0, C: 1 },
    targetOutput: 0,
    availableGates: ["AND", "OR", "NOT", "XOR"],
    par: 3,
  },
  {
    id: 10,
    title: "Final Challenge",
    description: "Build XNOR behaviour using basic gates only. A=1, B=1 → output 1.",
    hint: "XNOR = NOT XOR. Use XOR + NOT",
    inputs: { A: 1, B: 1 },
    targetOutput: 1,
    availableGates: ["AND", "OR", "NOT", "XOR"],
    par: 2,
  },
];

// Gate truth tables for engine
const GATE_TRUTH = {
  AND:  (a, b) => a & b,
  OR:   (a, b) => a | b,
  NOT:  (a)    => a ^ 1,
  XOR:  (a, b) => a ^ b,
  NAND: (a, b) => (a & b) ^ 1,
  NOR:  (a, b) => (a | b) ^ 1,
  XNOR: (a, b) => (a ^ b) ^ 1,
};

const GATE_INPUTS_NEEDED = {
  AND: 2, OR: 2, NOT: 1, XOR: 2, NAND: 2, NOR: 2, XNOR: 2,
};

const GATE_COLORS = {
  AND:  "#4f8ef7",
  OR:   "#7c3aed",
  NOT:  "#e11d48",
  XOR:  "#0891b2",
  NAND: "#d97706",
  NOR:  "#059669",
  XNOR: "#db2777",
};
